name: picacgPunch

on:

  push:
    branches: [ main ]    
    paths:
    - '**'
    - '!.gitignore'
    - '!README.md'
  
    
  workflow_dispatch:  
  schedule:
    - cron: '20 4 * * *'

jobs:

  build:    
  
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Time
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

      
    - name: Build
      run: dotnet build -c Release
    - name: Start time
      id: startTime
      run: |
        echo "sTime=$(date +'%Y-%m-%d %H:%M:%S')" >>$GITHUB_OUTPUT
    - name: Run
      id: run
      env:        
        accounts: ${{secrets.ACCOUNTS}}
      run: dotnet run -- ${accounts}
    - name: End time
      id: endTime
      run: |
        echo "eTime=$(date +'%Y-%m-%d %H:%M:%S')" >>$GITHUB_OUTPUT
    - name: Telegram Notify
      env:
        TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
        TELEGRAM_TO: ${{secrets.TELEGRAM_TO}}
      if: ${{ success() && env.TELEGRAM_TOKEN && env.TELEGRAM_TO }}
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *哔咔漫画 自动签到*
            
            ==开始时间:${{steps.startTime.outputs.sTime}}==
            ${{ steps.run.outputs.result  }}
            ==结束时间:${{steps.endTime.outputs.eTime}}==
            
            [任务详情](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ================
